### PR TITLE
add gguf support

### PR DESCRIPTION
**Pull request by zsz00**
Add  *.gguf model file support.
close https://github.com/cafaxo/Llama2.jl/issues/24

@cafaxo @jpsamaroo hope you help Implement the q5.jl and dot(x::AbstractVector{block_q6_K}, y::AbstractVector{block_q8_K})

### CODE REVIEW

**Comment by cafaxo** [comment]
Thanks, this is nice work that we should definitely merge.

It seems that besides GGUF support you are also adding support for q5 and q6 quantizations. Could you open another PR for these changes? That would make review easier.

It also seems like a test file (`test_1.jl`) slipped into this PR.

**Comment by zsz00** [comment]
ok, I cleaned  q5,  q6 existed in the original. 
Please review the code, I will  open another PR for q5.

**Comment by Sixzero** [comment]
I 'll also check it out! I 'll test first wether the accuracy is the same as if I would run .gguf with Llama.cpp

**Comment by Sixzero** [comment]
Q4_K_M seems to be not working out of the box, still checking what is going on. I saw your test file was with a Q4_K_S so I am going to test that, so I can see things working. Also this quantization file removal seem not complete, and I also think it is essential to be included in the feature. (So either we need a separate fast pull request on it, or just merge it with this feature since then it also gets tested by the feature.)

**Comment by cafaxo** [comment]
I reworked this PR a bit and merged GGUF support: https://github.com/cafaxo/Llama2.jl/commit/77f7b8fa40bb5b96d7f44df16546aa576aeaef09 (with @zsz00 as co-author).

**Pull request closed without merging**
