### PR TITLE
Add tokenizer and prompts

### PR DESCRIPTION
**Pull request by svilupp**
Opening this PR to start the discussion about bringing it to feature parity with llama2.c (eg, ability to run Llama2 models)

Among other things, this PR adds the tokenizer and the possibility to add prompts (ported from llama2.c). 
The entry point `sample()`as per README is kept, but the internals were restructured a bit. 
I don't feel strongly about the naming/structure/anything. I just wanted it to add this functionality -- feel free to counter it.

Usage:
```
model = load_model("models/model.bin", "models/tokenizer.bin");
sample(model, "Julia is the best"; temperature = 0.5f0)
```

Output on 15M model (smallest):

> Julia is the best in the world. She loves to dance and sing. Every day, she puts on her special dress and sung a song.
> One day, she was dancing in her room when she heard a noise. She looked around and saw her mom coming in. She quickly hid behind the curtain and waited.
> Her mom walked into the room and saw her. She smiled and said, "You look so cute, Julia!"
> Julia smiled back and said, "Thank you, Mommy!"
> The next day, Julia's mom asked her to clean up her room. Julia was so excited, so she quickly ran to her room and started to clean. She worked hard and when she was finished, she looked around and saw that her room was still tidy.
> Julia was so happy that she had listened to her mom. She put her dress in a special place and said, "Now, I can dance again!"
>  Once upon a time, there was a little girl named Lily. She loved to play outside in the sunshine. One day, she saw a big, dark cloud in the sky. It looked like a tornado was coming. She was scared and ran inside her
> achieved tok/s: 308.308152

Fixes:
- Changed starting token to `2` (=BOS) (irrelevant for the original benchmarking use case, but it generates slightly better stories)

Changes:
- Separate loading scripts from the inference (see `src/loading.jl`)
- Add a few structs to load relevant info into (see `src/types.jl`) + allow loading it only once
- Adds `str_lookup` and `bpe_encode` from Llama.c (needs better tests if we wanted to integrate it)

WDYT?

### CODE REVIEW

**Comment by svilupp** [comment]
And forget to mention that I added an auto-formatter spec (makes contributions easier)

**Comment by cafaxo** [comment]
Thank you very much for this PR!

I just pushed an implementation for prompting with https://github.com/cafaxo/Llama2.jl/commit/cdcdbe6fcb33be0f6cac61a18a72bfe7d08a18e8.

I feel like this PR does a bit too much at once: restructuring, reformatting, docs, etc.
It would be great if you split this into multiple PRs.

For example, I am not sure about the formatting changes -- is there a setting that keeps the indents a bit more intact?

**Comment by svilupp** [comment]
Sure, no problem. I'll close this one as it's the same as what you just pushed.

> Is there a setting that keeps the indents a bit more intact?
Not sure, but perhaps one of the available styles suits you more? See [here](https://domluna.github.io/JuliaFormatter.jl/stable/yas_style/)

1) what are your thoughts on the separation of loading and inference?

2) is `sample` the right function name for inference, if we succeeded to use Llama2 weights and use this as a personal assistant?

**Comment by cafaxo** [comment]
> what are your thoughts on the separation of loading and inference?

We should definitely separate that.

> is sample the right function name for inference, if we succeeded to use Llama2 weights and use this as a personal assistant?

I agree that `sample` is probably not quite right (since we are sampling multiple tokens at once). Do you have suggestions?
Maybe `generate` or `run`?

**Comment by cpfiffer** [comment]
I'd love to see this merged -- these seem like fantastic changes!

**Comment by svilupp** [comment]
Closing as all the functionality is already on main!

**Pull request closed without merging**
